### ISSUE TITLE
İzin

### ISSUE THREAD

**Issue by aligoren** [ustun/nasil-iyi-programci-olunur#1]
İzninizle ikinci dönem ilk derste sunum yapacağım bunu. Hocalar ve öğrenciler nasıl olur görsünler diye.

**Comment by ustun** [comment]
Tabii, videosu da var zaten isterseniz.

**Comment by aligoren** [comment]
Çok iyi olurdu gerçekten. Çok teşekkür ederim :)

**Comment by ustun** [comment]
Burada mevcut http://youtube.com/ustunozgur/videos
